# SwiftLint Configuration for Progress iOS App
# Enforces PRD requirements and Swift/SwiftUI best practices

# Included and Excluded Paths
included:
  - Progress/
excluded:
  - Progress/Preview Content/
  - Progress/Resources/Generated/
  - build/
  - .build/
  - DerivedData/

# Custom Rules
custom_rules:
  # Rule: No UIKit imports (PRD requirement)
  no_uikit_import:
    name: "No UIKit Import"
    regex: "^import UIKit$"
    message: "UIKit imports are forbidden. Use SwiftUI only per PRD requirements."
    severity: error
    
  # Rule: No hardcoded colors
  no_hardcoded_colors:
    name: "No Hardcoded Colors"
    regex: "Color\\.(red|blue|green|black|white|gray|orange|purple|pink|yellow|clear|primary|secondary)"
    message: "Use design tokens from Colours.swift instead of hardcoded colors."
    severity: error
    
  # Rule: No hardcoded fonts
  no_hardcoded_fonts:
    name: "No Hardcoded Fonts"
    regex: "Font\\.(largeTitle|title|title2|title3|headline|subheadline|body|callout|footnote|caption|caption2)"
    message: "Use design tokens from Typography.swift instead of hardcoded fonts."
    severity: error
    
  # Rule: SwiftGen localization
  hardcoded_strings:
    name: "Use SwiftGen Localization"
    regex: 'Text\s*\(\s*"[^"]*"\s*\)'
    message: "Use SwiftGen L10n keys instead of hardcoded strings in Text views."
    severity: warning
    
  # Rule: No force unwrapping in production code
  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: "!(?![=])"
    message: "Avoid force unwrapping. Use safe unwrapping or guard statements."
    severity: warning
    excluded: ".*Test.*\\.swift"

# Enabled Rules
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled Rules
disabled_rules:
  - todo # Allow TODO comments during development
  - function_body_length # SwiftUI views can be long
  - type_body_length # SwiftUI views can be long

# Rule Configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - uri
    - x
    - y
    - z

large_tuple:
  warning: 3
  error: 4

function_parameter_count:
  warning: 6
  error: 8

# SwiftUI specific configurations
closure_body_length:
  warning: 30
  error: 50

# File header template (optional)
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Progress
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/

# Custom reporter (optional)
reporter: "xcode"

# Exclude generated files
exclude_from_report:
  - "*/Generated/*"
  - "*/SwiftGen/*"
  - "*/Resources/Generated/*" 